"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('admin_character_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('prices',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sell', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('type_id', 'date')
    )
    op.create_table('sde_groups',
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('sde_regions',
    sa.Column('region_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('sde_systems',
    sa.Column('system_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('security', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('sde_type_materials',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type_id', 'material_type_id')
    )
    op.create_table('sde_types',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('portion_size', sa.Integer(), nullable=False),
    sa.Column('ore_class', sa.String(length=16), nullable=False),
    sa.Column('moon_rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sde_types_group_id'), 'sde_types', ['group_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('primary_character_id', sa.BigInteger(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reprocess_yield', sa.Float(), server_default='0.85', nullable=False),
    sa.Column('price_basis', sa.String(length=8), server_default='buy', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_hash', sa.String(length=255), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=True),
    sa.Column('corporation_name', sa.String(length=255), nullable=True),
    sa.Column('alliance_id', sa.BigInteger(), nullable=True),
    sa.Column('alliance_name', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('token_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_index(op.f('ix_characters_next_sync_at'), 'characters', ['next_sync_at'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('mining_ledger',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'date', 'solar_system_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_ledger')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_next_sync_at'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_index(op.f('ix_sde_types_group_id'), table_name='sde_types')
    op.drop_table('sde_types')
    op.drop_table('sde_type_materials')
    op.drop_table('sde_systems')
    op.drop_table('sde_regions')
    op.drop_table('sde_groups')
    op.drop_table('prices')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
