"""structure finder

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_stargates',
    sa.Column('from_system_id', sa.Integer(), nullable=False),
    sa.Column('to_system_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('from_system_id', 'to_system_id')
    )
    op.create_table('sde_stations',
    sa.Column('station_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('has_reprocessing', sa.Boolean(), nullable=False),
    sa.Column('reprocessing_efficiency', sa.Float(), nullable=False),
    sa.Column('reprocessing_tax', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_sde_stations_system_id'), 'sde_stations', ['system_id'], unique=False)
    op.create_table('sde_structure_types',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('rig_size', sa.Integer(), nullable=True),
    sa.Column('refining_bonus', sa.Float(), nullable=False),
    sa.Column('can_reprocess', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('structures',
    sa.Column('structure_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('has_market', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_manufacturing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_listed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('structure_id')
    )
    op.create_index(op.f('ix_structures_system_id'), 'structures', ['system_id'], unique=False)
    op.create_table('structure_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('has_reprocessing', sa.Boolean(), nullable=True),
    sa.Column('rig_tier', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_reports_structure_id'), 'structure_reports', ['structure_id'], unique=False)
    op.create_table('structure_access',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'structure_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure_access')
    op.drop_index(op.f('ix_structure_reports_structure_id'), table_name='structure_reports')
    op.drop_table('structure_reports')
    op.drop_index(op.f('ix_structures_system_id'), table_name='structures')
    op.drop_table('structures')
    op.drop_table('sde_structure_types')
    op.drop_index(op.f('ix_sde_stations_system_id'), table_name='sde_stations')
    op.drop_table('sde_stations')
    op.drop_table('sde_stargates')
    # ### end Alembic commands ###
